### ISSUE TITLE
wiki 업로드용 이미지 모음

### ISSUE THREAD

**Issue by grcenneat** [WinterSpringProject/PROJECT-PIND-FE#1]
> wiki에 업로드할 이미지 주소를 얻기 위해 오픈한 이슈입니다.
> 새로운 이미지는 댓글로 추가하시면 됩니다.

![cardview_sample](https://user-images.githubusercontent.com/13804135/108166865-2783fa00-7138-11eb-8cf9-dfb23f94215a.png)

주제 : 만들어야 할 페이지 View
목표 : 브라우저에 카드뷰 한 개 띄우기

**Comment by Ohhong** [comment]
무엇을 위한 이미지인가요?

**Comment by devbluesea** [comment]
> 무엇을 위한 이미지인가요?

카드뷰에 들어갈 정보들을 배치한 이미지 입니다.
그리고 제일 먼저 카드 하나 만들어보기 하고있습니다.

**Comment by gyumnnii** [comment]
@devbluesea 

다른 분들이 보기 쉽게 이슈명으로 어떤 이미지인지 명시해주는 편이 좋을 것 같네요!

**Comment by devbluesea** [comment]
> @devbluesea
> 
> 다른 분들이 보기 쉽게 이슈명으로 어떤 이미지인지 명시해주는 편이 좋을 것 같네요!

네~ 이슈명 수정하겠습니다

**Comment by Ohhong** [comment]
@devbluesea 
이슈에 대한 내용도 작성해 주는 것이 좋아보입니다.
ex) 목표, 주제, 논의 되어야할 내용 등

**Comment by devbluesea** [comment]
> @devbluesea
> 이슈에 대한 내용도 작성해 주는 것이 좋아보입니다.
> ex) 목표, 주제, 논의 되어야할 내용 등

네 알겠습니다. 잘 몰랐는데 수정하고 다음부터는 이슈 잘 올리겠습니다.

**Comment by grcenneat** [comment]
이 이슈는 앞으로도 wiki에 이미지 넣을 일이 종종 있을 것 같아서
댓글에 이미지 올려서 주소 얻는 용도로 이용하려고 오픈한 이슈입니다 
제가 목적에 맞게 이슈명 다시 변경할게요 !!

**Comment by Ohhong** [comment]
@hysimok 
이미지 주소를 얻는 것은 굳이 이슈가 열려있지 않아도 댓글을 달지 않아도 사용 가능할 것 같은데 확인 부탁드릴게요~

**Comment by grcenneat** [comment]
@Ohhong 넵넵 이슈 닫아놓고 본문 수정으로 올리는 방식으로 하겠습니다 !
