### ISSUE TITLE
상태관리 라이브러리 도입 검토 (Context API, Redux, Recoil 비교)

### ISSUE THREAD

**Issue by grcenneat** [WinterSpringProject/PROJECT-PIND-FE#16]
현재 PIND에서 사용하고 있는 props

- NavBar
    - CategoryList에서 `navCategory`
    - CategoryItem에서 `categoryList`
- CardView
    - CardViewList 에서 `cards`
    - CardViewListItem 에서 `card`

> 현재는 state가 많지 않지만, 앞으로 컴포넌트가 많아지면  관리하기가 어려워질 것입니다. 다른 컴포넌트에 전달해야할 props가 많아지고 컴포넌트 간 props 전달하는 경로 또한 복잡해지기 때문입니다. 따라서 Context API, Redux, Recoil 등의 상태관리 라이브러리를 활용하려고 합니다.

> 어떤 라이브러리가 있는지, 각각의 특징은 뭔지 알아보았습니다.

### Context API

- 전역으로 관리해야할 데이터가 있을 때 유용하다.
- ex) 사용자 로그인 정보, 환경설정, 테마 등
- Context API를 쓰지 않으면 최상위 컴포넌트에서 state를 정의한 후 여러 컴포넌트를 거쳐 props를 전달했지만, Context API를 활용하면 어떤 컴포넌트에서 필요한 값을 단숨에 받아올 수 있다.
- Context 생성 ⇒ Consumer 사용해 Context 내부의 값 조회 ⇒ Provider로 값 수정

### Redux

- 가장 많이 사용하는 상태관리 라이브러리
- 상태 업데이트 관련 로직을 다른 파일로 분리시켜 더 효율적으로 관리할 수 있습니다.
- 전역 상태관리만 할거라면 Context API로 충분하지만, 프로젝트가 크다면 개발자도구 지원 + 미들웨어 제공 하는 리덕스 필수
- 아래 개념 알아야한다.
    - action
    - action creator
    - reducer
    - store
    - dispatch
    - subscribe
- 참고
- 리액트를 다루는 기술
- [https://medium.com/@ca3rot/아마-이게-제일-이해하기-쉬울걸요-react-redux-플로우의-이해-1585e911a0a6](https://medium.com/@ca3rot/%EC%95%84%EB%A7%88-%EC%9D%B4%EA%B2%8C-%EC%A0%9C%EC%9D%BC-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%EC%89%AC%EC%9A%B8%EA%B1%B8%EC%9A%94-react-redux-%ED%94%8C%EB%A1%9C%EC%9A%B0%EC%9D%98-%EC%9D%B4%ED%95%B4-1585e911a0a6)

### Recoil

- 가장 최근에 출시된 라이브러리
- 매우 간단하고 간단하다.
- atom과 selector 라는 개념 사용
- useState Hook 처럼 작동해서 입문하기 좋다.
- Recoil을 사용하면서 상태 관리의 흐름을 배울 수 있을지는 모르겠음.
- [https://velog.io/@wooder2050/리코일Recoil는-왜-만든-건데](https://velog.io/@wooder2050/%EB%A6%AC%EC%BD%94%EC%9D%BCRecoil%EB%8A%94-%EC%99%9C-%EB%A7%8C%EB%93%A0-%EA%B1%B4%EB%8D%B0)

> 가장 널리 쓰이기도하고, 상태관리 흐름을 공부하기 위한 목적으로 Redux 를 사용해보기로 하였습니다.

**Comment by gyumnnii** [comment]
Redux를 도입하시기로 했군요! 좋습니다.

redux를 상태관리를 위해서만 사용할 수도 있고 
redux-thunk, redux-saga라는 미들웨어를 이용하여 비동기 처리(대부분 API호출을 통한 데이터 fetching 과정에서 많이 사용해요!)하는 기능도 할 수 있게 만들곤 합니다.

추후에 api call 함수를 컴포넌트 내부에서 직접 호출하는 식으로 코드를 작성하실텐데 해당 과정의 번거로운 점을 몸소 느껴보시고 위에서 언급한 redux 비동기 처리에 관한 라이브러리도 공부해보셨으면 좋겠어요 ^~^ (지금 당장 적용하기엔 무리가 있을 수 있으니 현재 프로젝트에 사용하는 것은 권장하지는 않습니다!)

추가적으로 redux를 사용하는 패턴이 여러가지가 있는데 그 중에서 [ducks 패턴](https://velog.io/@dolarge/React-Redux-Ducks-패턴)에 대한 내용을 참고해보셔도 좋을 것 같아요! 꼭 해당 패턴을 사용하라는 건 아니고 두 분께 편한 방법을 적용해주시면 될 것 같습니다.

**Comment by grcenneat** [comment]
리덕스를 이용하고, ducks 패턴도 도입하기로 결정하였습니다.
issue close 하겠습니다.
