### ISSUE TITLE
상세페이지, 필요한 컴포넌트

### ISSUE THREAD

**Issue by devbluesea** [WinterSpringProject/PROJECT-PIND-FE#4]
<br/>
<br/>

<b>첫 페이지 뷰</b>
- 컬러는 추후에 정할 예정이기 때문에 지금은 그레이스케일과 뉴트럴 컬러로 사용함
- 위에서 부터 아래로 네비바 -> 지역별, 주제별 카테고리 카드 -> 카테고리 선택하는 부분 -> 검색 바 -> 프로젝트 카드뷰 -> 밑 단(사이트 정보, 카피라이트 등 추가예정)

<br/>
<br/>

![Web 1920 – 1](https://user-images.githubusercontent.com/23551596/108841589-55c37700-761b-11eb-9bd4-4c4cc4261e72.png)

___

<b>두 번째 페이지 뷰</b>
-프로젝트 카드뷰를 눌렀을 때 나오는 화면
-프로젝트 이미지 -> 프로젝트 소개 -> 그룹장 소개 -> 참여자 수, 장소, 기간 등 정보(추가 예정)

<br/>
<br/>

![Web 1920 – 2](https://user-images.githubusercontent.com/23551596/108841577-51975980-761b-11eb-9eb4-76a1d91ab535.png)

논의할 점 
1. 필요한 정보들이 빠짐 없이 있는지
2. 더 필요한 페이지가 있는지 논의 필요 

추가할 것 
1. 지역별 눌렀을 때 지도와 나의 위치랑 같이 나타나는 화면
2. 상세페이지가 조금 더 추가되면 와이어프레임으로 나타낼 예정입니다.
3. 컬러는 추후에 정할 예정이기 때문에 지금은 그레이스케일과 뉴트럴 컬러로 잡아놨습니다.

**Comment by Ohhong** [comment]
@devbluesea
앗 단순히 제 생각인데 뭔가 글의 설명이 아래에 있으니
글을 읽고 다시 그림을 봐야하는 경우가 있는 것 같아요..!
저도 글을 잘 쓰는 편은 아니지만 이런 부분도 생각해주시면
협업 관점에서 좋은 어필을 할 수 있지 않을까 싶습니다~

**Comment by devbluesea** [comment]
@Ohhong 
정말 그렇네요ㅎㅎ 저는 제가 만들어서 글만 봐도 괜찮았는데
그 부분은 생각하지도 못했는데 감사합니다.
이슈는 수정 완료했습니다!
