### ISSUE TITLE
[질문] Back-End의 API가 아직 없을 때 프론트를 설계하는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by devbluesea** [WinterSpringProject/PROJECT-PIND-FE#9]
API가 아직 없을 때 프론트를 어떻게 만들지 계획과 기초 설계는 어떻게 해야하나요?

@Ohhong

**Comment by gyumnnii** [comment]
현재 백엔드와 협의된 API가 있는 것으로 알고 있습니다.

해당 API 스펙에 맞게 가짜 mock(가짜) 데이터를 만들어서 구현에 이용하는 방법을 추천드립니다.

혹은 백엔드 쪽에 요청하여 mock 데이터를 내려주는 mock API를 달라고 하셔도 좋습니다.

**Comment by devbluesea** [comment]
@gyumnnii  답변 감사합니다! 궁금증이 해결되었습니다.
